# Generated by Django 5.1.3 on 2024-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FEMALE", "FEMALE"),
                            ("MALE", "MALE"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "BEGINNER"),
                            ("INTERMEDIARY", "INTERMEDIARY"),
                            ("ADVANCED", "ADVANCED"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
