# Generated by Django 5.1.3 on 2024-11-25 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=20)),
                ('category', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIARY', 'INTERMEDIARY'), ('ADVANCED', 'ADVANCED')], max_length=20)),
            ],
        ),
    ]
