# Generated by Django 5.1.3 on 2024-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_student_created_at_student_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="user_id",
            new_name="user",
        ),
    ]
