# Generated by Django 5.1.3 on 2024-12-04 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_rename_user_id_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
