# Generated by Django 5.1.4 on 2025-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_email_remove_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='frequency_of_classes',
            field=models.CharField(choices=[('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('4X', '4X'), ('5X', '5X'), ('6X', '6X')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
