# Generated by Django 5.1.4 on 2025-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_frequency_of_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='frequency_of_classes',
            field=models.CharField(choices=[('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('4X', '4X'), ('5X', '5X')], max_length=2),
        ),
    ]
