# Generated by Django 5.1.4 on 2025-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='playing_side',
            field=models.CharField(choices=[('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
