# Generated by Django 5.1.4 on 2025-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_playing_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
