# Generated by Django 5.1.4 on 2025-02-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
