# Generated by Django 5.1.4 on 2025-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.CharField(choices=[('IPANEMA', 'IPANEMA'), ('BARRA', 'BARRA')], default='IPANEMA', max_length=7),
            preserve_default=False,
        ),
    ]
