# Generated by Django 5.1.4 on 2025-01-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_court_status'),
        ('list_courts', '0001_initial'),
        ('lists', '0003_remove_list_category_remove_list_date_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcourt',
            name='court',
        ),
        migrations.RemoveField(
            model_name='listcourt',
            name='lists',
        ),
        migrations.AddField(
            model_name='listcourt',
            name='court',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_courts', to='courts.court'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listcourt',
            name='lists',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='list_courts', to='lists.list'),
            preserve_default=False,
        ),
    ]
