# Generated by Django 5.1.4 on 2025-01-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admission_created_at_alter_admission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='created_at',
        ),
    ]
