# Generated by Django 5.1.4 on 2025-01-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Params',
            new_name='ListParams',
        ),
    ]
