# Generated by Django 5.1.4 on 2025-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_rename_params_listparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listparams',
            name='category',
            field=models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIARY', 'INTERMEDIARY'), ('ADVANCED', 'ADVANCED'), ('WARNING', 'WARNING')], max_length=12),
        ),
    ]
