# Generated by Django 5.1.4 on 2025-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0004_alter_listparams_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listparams',
            name='unit',
            field=models.CharField(choices=[('IPANEMA', 'IPANEMA'), ('BARRA', 'BARRA')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
