# Generated by Django 5.1.4 on 2025-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0007_alter_listparams_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listparams',
            name='class_time',
        ),
        migrations.AlterField(
            model_name='listparams',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
