# Generated by Django 5.1.4 on 2025-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0008_remove_listparams_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listparams',
            name='created_by',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
