# Generated by Django 5.1.3 on 2024-11-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="profile_img",
            field=models.TextField(blank=True, null=True),
        ),
    ]
