# Generated by Django 5.1.4 on 2025-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_created_at_coach_updated_at_alter_coach_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='profile_img',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
