# Generated by Django 5.1.3 on 2024-11-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0003_student_profile_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_day", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "BEGINNER"),
                            ("INTERMEDIARY", "INTERMEDIARY"),
                            ("ADVANCED", "ADVANCED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
