# Generated by Django 5.1.4 on 2025-02-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_list_category_remove_list_date_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='class_time',
        ),
    ]
