# Generated by Django 5.1.4 on 2025-02-18 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='class_time',
            field=models.TimeField(choices=[(datetime.time(6, 0), '06:00'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(6, 15), '06:15'), (datetime.time(7, 15), '07:15'), (datetime.time(8, 15), '08:15')], default='08:00'),
            preserve_default=False,
        ),
    ]
