# Generated by Django 5.1.4 on 2025-02-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_class_time'),
        ('params', '0008_remove_listparams_class_time_and_more'),
        ('students', '0015_student_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('student', 'list_params')},
        ),
    ]
